# Generated by Django 3.0 on 2021-06-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewCustomer',
            new_name='Customer',
        ),
    ]
