# Generated by Django 3.0 on 2021-06-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210603_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=25)),
                ('amount', models.IntegerField()),
                ('Receiver_name', models.CharField(max_length=25)),
            ],
        ),
    ]
