# Generated by Django 3.0.5 on 2021-07-20 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='Receiver_name',
            new_name='receiver_name',
        ),
    ]
